# Generated by Django 3.2.7 on 2021-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('photo_1', models.ImageField(blank=True, upload_to='media/images/')),
                ('body', models.TextField()),
                ('photo_2', models.ImageField(blank=True, upload_to='media/images/')),
                ('body_2', models.TextField()),
            ],
        ),
    ]
