# Generated by Django 3.2.4 on 2021-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0002_auto_20211031_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
