# Generated by Django 4.0.1 on 2022-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0003_alter_yangiliklar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='sherzamon')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='sherzamon')),
            ],
        ),
        migrations.DeleteModel(
            name='Yangiliklar',
        ),
    ]
