# Generated by Django 4.0.1 on 2022-01-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0004_news_delete_yangiliklar'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
