# Generated by Django 4.0 on 2022-01-26 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0005_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
