# Generated by Django 3.2.7 on 2021-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanlar',
            name='bolim1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='bolim2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='bolim3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='bolim4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='text1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='text2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='text3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='text4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fanlar',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
