# Generated by Django 3.2.7 on 2021-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0003_auto_20210914_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('tell', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
