# Generated by Django 3.2.7 on 2021-09-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0007_auto_20210917_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oqituvchilar',
        ),
    ]
