# Generated by Django 3.2.7 on 2021-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0008_delete_oqituvchilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('tell', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='media/images/')),
            ],
        ),
    ]
