# Generated by Django 3.2.7 on 2021-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0009_oqituvchilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='vaqt',
            field=models.CharField(max_length=10),
        ),
    ]
