# Generated by Django 3.2.7 on 2021-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0010_alter_fanlar_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='text1',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
