# Generated by Django 3.2.7 on 2021-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0011_alter_fanlar_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanlar',
            name='text1_decription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='text1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
