# Generated by Django 3.2.7 on 2021-09-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0012_auto_20210929_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='text1_decription',
            field=models.TextField(blank=True),
        ),
    ]
