# Generated by Django 3.2.7 on 2021-10-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0014_auto_20210929_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yangiliklar',
        ),
    ]
