# Generated by Django 3.2.7 on 2021-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0015_delete_yangiliklar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oqituvchilar',
        ),
        migrations.AddField(
            model_name='fanlar',
            name='narx',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
