# Generated by Django 3.2.4 on 2021-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0018_auto_20211105_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='derector_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='derector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='derector_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
