# Generated by Django 3.2.4 on 2021-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0020_auto_20211110_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageDerector',
        ),
        migrations.DeleteModel(
            name='AboutPagePhoto',
        ),
        migrations.DeleteModel(
            name='AboutPageVideo',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='derector_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='derector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='derector_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/video/'),
        ),
    ]
