# Generated by Django 4.0 on 2022-01-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0025_kurslar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('facebook', models.CharField(blank=True, max_length=86, null=True)),
                ('instagram', models.CharField(blank=True, max_length=25, null=True)),
                ('telegram', models.CharField(blank=True, max_length=88, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fanlar.kurslar')),
            ],
        ),
    ]
