# Generated by Django 4.0 on 2022-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0026_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
