# Generated by Django 4.0 on 2022-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0027_teachers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurslar',
            name='offline_price',
            field=models.IntegerField(blank=True, default=700000, null=True),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='online_price',
            field=models.IntegerField(blank=True, default=700000, null=True),
        ),
    ]
