# Generated by Django 4.0 on 2022-01-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0028_kurslar_offline_price_kurslar_online_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('kurs', models.CharField(blank=True, max_length=145, null=True)),
            ],
        ),
    ]
